# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.17
_src_path: gh:westerveltco/django-twc-package
author_email: josh@joshthomas.dev
author_name: Josh Thomas
current_version: 0.1.3
django_versions:
- '3.2'
- '4.2'
- '5.0'
docs_domain: westervelt.dev
github_owner: westerveltco
github_repo: wagtail-heroicons
module_name: wagtail_heroicons
package_description: Add Heroicons to your Wagtail site
package_name: wagtail-heroicons
python_versions:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
- '3.12'
test_django_main: true
versioning_scheme: SemVer
