name: release

on:
  release: 
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "PYPI_INDEX=test" >> $GITHUB_ENV
          echo "PYPI_PASSWORD=${{ secrets.TEST_PYPI_PASSWORD }}" >> $GITHUB_ENV
      - if: ${{ !env.PYPI_PASSWORD }}
        run: |
          echo "PYPI_INDEX=main" >> $GITHUB_ENV
          echo "PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}" >> $GITHUB_ENV
      - name: Build and publish to PyPI
        run: |
          hatch build
          hatch publish -r ${{ env.PYPI_INDEX }} -u __token__ -a ${{ env.PYPI_PASSWORD }}